config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root to: 'home#index'
  get 'roomtype/index'
  get 'roomtype/room1'
  get 'roomtype/room2'
  get 'roomtype/room3'
  get 'roomtype/room4'
  get 'roomtype/room5'
  get 'roomtype/room6'
  get 'bookings/index'
  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  def self.find_in_bkdb(search_terms)
    if search_terms
      bookings = Booking.find_by(name: search_terms)
      if bookings
        self.where(name: bookings.name)
      else
        return 7
      end
    else
      return nil
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about_page = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @booking_page = true
    @bookings = Booking.find_in_bkdb(params[:search_terms])
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:name, :date, :days, :peoples, :room_type, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_page = true
  end
end

app/controllers/roomtype_controller.rb
class RoomtypeController < ApplicationController
  def index
    @roomtype_page = true
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<script>
  function onClick(element) {
    document.getElementById("img01").src = element.src;
    document.getElementById("modal01").style.display = "block";
  }
</script>
<body>
<div class="content">
  <div class="container">
    <header>
      <h1><u>About</u></h1>
    </header>
    <s1>
      <h2> Team member </h2>
      <div class="groupname">
        กัญญาภรณ์ สร้อยคำพา 5910520054<br>
        วิศววิท ฤทธิศรธนู 5910613214<br>
        โฆษิต สุขบรรเทิง 5910613388<br>
        ธนพล บุญมาก 5910680379
      </div>
      <br>
      <br>
      <h2>Links</h2>
      <a href="https://drive.google.com/file/d/1u6TnvV_R2VMEPe9sHUn399EErXJepg51/view?usp=sharing"><button class="button button1">Proposal</button></a>
      <a href="https://gitlab.com/5910613388/layana"><button class="button button1">Git</button></a>
      <a href="https://www.pivotaltracker.com/n/projects/2406996"><button class="button button1">Pivotal tracker</button></a>
    </s1>
    <s2>
      <h2>User Story</h2>
      <div>
        <img id="myImg" src="/images/1.jpg" width="35%" onclick="onClick(this)" class="modal-hover-opacity">
        <img id="myImg" src="/images/2.jpg" width="35%" onclick="onClick(this)" class="modal-hover-opacity">
        <img id="myImg" src="/images/3.jpg"width="35%" onclick="onClick(this)" class="modal-hover-opacity">
        <img id="myImg" src="/images/4.jpg"width="35%" onclick="onClick(this)" class="modal-hover-opacity">
        <img id="myImg" src="/images/5.jpg" width="35%" onclick="onClick(this)" class="modal-hover-opacity">
        <img id="myImg" src="/images/6.jpg" width="35%" onclick="onClick(this)" class="modal-hover-opacity">
      </div>
      <div id="modal01" class="modal" onclick="this.style.display='none'">
        <span class="close">&times;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <div class="modal-content">
          <img id="img01" style="max-width:100%">
        </div>
      </div>
    </s2>
  </div>
</div>
</body>

app/views/bookings/_form.html.haml
= form_for @booking do |f|
  - if @booking.errors.any?
    #error_explanation
      %h2= "#{pluralize(@booking.errors.count, "error")} prohibited this booking from being saved:"
      %ul
        - @booking.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name, required: true
  .field
    = f.label :date
    = f.date_select :date, required: true
  .field
    = f.label :days
    = f.number_field :days, required: true
  .field
    = f.label :room_type
    = f.select :room_type, [["Grand Garden Pavilion King Room",1],["Grand Garden Pavilion Twin Room",2], ["Terrace Suite",3], ["Ocean Delux Villa",4], ["Beach Villa",5], ["La maison",6]],{}, {required: true, id: 'roomtype', :onChange=>"handler();", :prompt => "Select room type."}
  #state_people.field
    = f.label :peoples
    = f.select :peoples,[[1,1],[2,2]]
  .field
    = f.label :phone
    = f.text_field :phone, required: true
  .actions
    = f.submit 'Book'

:javascript
  document.getElementById('state_people').style.display = 'none';
  function handler()
  {
    var type=document.getElementById("roomtype").value;
    var s = document.getElementById('booking_peoples');

    if(type == 1 || type == 2 || type == 3 || type == 4 || type == 5)
    {
      document.getElementById('state_people').style.display = 'inline';
    }
    else if(type == 6)
    {
      document.getElementById('state_people').style.display = 'inline';
      s.options[s.options.length]= new Option('3', '3');
      s.options[s.options.length]= new Option('4', '4');
    }
    else{
      document.getElementById('state_people').style.display = 'none';
    }
  }

app/views/bookings/edit.html.haml
.booking-body
  <div align="center">
  %h1 Editing booking

  = render 'form'

  = link_to 'Show', @booking
  \|
  = link_to 'Back', bookings_path
  <div>

app/views/bookings/index.html.haml
= form_tag(bookings_path, method: :get) do
  <div class="wrap">
  <div class="search">
  = text_field_tag(:search_terms, params[:search_terms], class:"searchTerm" , placeholder:"Search your booking here...", required: true)
  <button type="submit" class="searchButton" value="search">
  <i class="fa fa-search"></i>
  </button>
  </div>
  </div>
<div class="booking-body">
<div align="center">

%h1 Listing bookings
-if @bookings.nil?
-elsif @bookings == 7
  = 'There are no booking that you are looking for.'
-else
  %table
    %thead
      %tr
        %th Name
        %th Date
        %th Days
        %th Peoples
        %th Room type
        %th Phone
        %th
        %th
        %th

    %tbody
      - @bookings.each do |booking|
        %tr
          %td= booking.name
          %td= booking.date
          %td= booking.days
          %td= booking.peoples
          %td= booking.room_type
          %td= booking.phone
          %td= link_to 'Show', booking
          %td= link_to 'Edit', edit_booking_path(booking)
          %td= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Booking', new_booking_path, class:'button button1'

-#= form_tag(bookings_path, method: :get) do
-#  = text_field_tag(:search, params[:search])
-#  = submit_tag

-#= form_tag(bookings_path, method: :get) do
-#  <div class="wrap">
-#  <div class="search">
-#  = text_field_tag(:search, params[:search], class:"searchTerm" , placeholder:"Search your booking here...")
-#  <button type="submit" class="searchButton">
-#  <i class="fa fa-search"></i>
-#  = submit_tag
-#  </button>
-#  </div>
-#  </div>

app/views/bookings/new.html.haml
<div align = "center">
.booking-body
  %h1 New booking

  = render 'form'

  = link_to 'Back', bookings_path
</div>

app/views/bookings/show.html.haml
.booking-body
  %p#notice= notice

  %p
    %b Name:
    = @booking.name
  %p
    %b Date:
    = @booking.date
  %p
    %b Days:
    = @booking.days
  %p
    %b Peoples:
    = @booking.peoples
  %p
    %b Room type:
    -if @booking.room_type == '1'
      = "Grand Garden Pavilion King Room"
    -elsif @booking.room_type == '2'
      = 'Grand Garden Pavilion Twin Room'
    -elsif @booking.room_type == '3'
      = 'Terrace Suite'
    -elsif @booking.room_type == '4'
      = 'Ocean Delux Villa'
    -elsif @booking.room_type == '5'
      = 'Beach Villa'
    -elsif @booking.room_type == '6'
      = 'La maison'

  %p
    %b Phone:
    = @booking.phone

  = link_to 'Edit', edit_booking_path(@booking)
  \|
  = link_to 'Back', bookings_path

app/views/home/index.html.erb
<div class="layana">
  Layana
</div>

<div class="booking-body">
  <div >

      <main >
        <div align="center">
          <br>
          <table id="table_content">
            <tr>
              <td>
                <img src="/images/p-01.jpg" width="100%">
              </td>
              <td style="padding: 50px">
                <h3>
                  สัมผัสบริการระดับโลกที่ <br>Layana Resort & Spa<br><br>
                </h3>
                <p>
                  Layana Resort & Spa
                  เป็นที่พักซึ่งเหมาะสำหรับผู้ใหญ่และล้อมรอบด้วยแมกไม้เขตร้อนเขียวชอุ่มบนพื้นที่เกาะลันตา
                  และมีวิวทะเลสวยงาม ที่พักมีสระว่ายน้ำอินฟินตี้กลางแจ้งและห้องพักมีอินเทอร์เน็ตไร้สาย (WiFi) ฟรี
                  ผู้เข้าพักสามารถเดินจากรีสอร์ทไปหาดยาวได้โดยตรง
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding: 50px">
                <p>
                  Layana Resort ตั้งอยู่บนผืนทรายสีขาวภายในเขตอุทยานแห่งชาติหมู่เกาะลันตา
                  สนามบินกระบี่อยู่ห่างออกไปโดยใช้เวลาเดินทางด้วยรถยนต์เป็นเวลา 2 ชม.
                  หรือ 70 กม. จากรีสอร์ท ที่พักมีบริการรับส่งสนามบินเมื่อแจ้งคำขอ และมีค่าธรรมเนียมเพิ่มเติม

                </p>
              </td>
              <td>
                <img src="/images/p-02.jpg" width="100%">
              </td>
            </tr>
            <tr>
              <td>
                <img src="/images/p-03.jpg" width="100%">
              </td>
              <td style="padding: 50px">
                <p>
                  ห้องพักที่ Layana Resort มีสถาปัตยกรรมไทยสมัยใหม่และตกแต่งด้วยผ้าไหมและเฟอร์นิเจอร์ไม้เนื้อแข็ง
                  ห้องพักแต่ละห้องมีโทรทัศน์ระบบช่องสัญญาณดาวเทียม
                  เครื่องเล่นดีวีดี เตียงนอนเล่น ห้องน้ำในตัวพร้อมฝักบัว และอ่างอาบน้ำแยกเป็นสัดส่วน

                </p>
              </td>
            </tr>
            <tr>
              <td style="padding: 50px">
                <p>
                  ผู้เข้าพักสามารถออกกำลังกายเรียกเหงื่อที่ศูนย์ออกกำลังกาย
                  หรือผ่อนคลายด้วยการอ่านหนังสือในห้องสมุดซึ่งมีหนังสือหลากประเภท สปา Linger Longer Spa
                  ซึ่งได้รับรางวัลของรีสอร์ทตั้งอยู่ในสวนและมีบริการนวดผ่อนคลายและทรีทเมนท์ผิวหน้า

                </p>
              </td>
              <td>
                <img src="/images/p-04.jpg" width="100%">
              </td>
            </tr>
            <tr>
              <td>
                <img src="/images/p-05.jpg" width="100%">
              </td>
              <td style="padding: 50px">
                <p>
                  ห้องอาหาร Sea Sky Restaurant มีบริการอาหารนานาชาติ อาหารทะเลสดใหม่ และอาหารไทยต้นตำรับหลากรายการ
                  ซึ่งท่านสามารถรับบริการได้ที่ริมสระว่ายน้ำ
                  หรือบนชายหาด ขณะที่บาร์ให้บริการเครื่องดื่มเพื่อเพิ่มความสดชื่น

                </p>
              </td>
            </tr>
            <tr>
              <td style="padding: 50px">
                <p>
                  ที่พักแห่งนี้ได้รับการลงความเห็นว่ามีทำเลดีและคุ้มค่าเงินที่สุดในเกาะลันตา!
                  โดยผู้เข้าพักชอบทำเลของที่นี่มากกว่าเมื่อเปรียบเทียบกับที่พักอื่น ๆ ในย่านนี้
                </p>
              </td>
              <td>
                <img src="/images/p-06.jpg" width="100%">
              </td>
            </tr>
          </table>
          <br>
        </div>
      </main>
    </div>

  </div>
</div>

app/views/layouts/_header-about.html.erb
<header>
  <div class="topnav">
    <a href="/">Home</a>
    <a href="/roomtype/index">RoomType</a>
    <a href="/bookings/index">Booking</a>
    <a class="active" href="/about/index">About</a>
  </div>
</header>

app/views/layouts/_header-booking.html.erb
<header>
  <div class="topnav">
    <a href="/">Home</a>
    <a href="/roomtype/index">RoomType</a>
    <a class="active" href="/bookings/index">Booking</a>
    <a href="/about/index">About</a>
  </div>
</header>

app/views/layouts/_header-home.html.erb
<header>
  <div class="topnav">
    <a class="active" href="/">Home</a>
    <a href="/roomtype/index">RoomType</a>
    <a href="/bookings/index">Booking</a>
    <a href="/about/index">About</a>
  </div>
</header>

app/views/layouts/_header-roomtype.html.erb
<header>
  <div class="topnav">
    <a href="/">Home</a>
    <a class="active" href="/roomtype/index">RoomType</a>
    <a href="/bookings/index">Booking</a>
    <a href="/about/index">About</a>
  </div>
</header>

app/views/layouts/_header.html.erb
<header>
  <div class="topnav">
    <a href="/">Home</a>
    <a href="/roomtype/index">RoomType</a>
    <a href="/bookings/index">Booking</a>
    <a href="/about/index">About</a>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Layana</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= render 'layouts/header' %>

    <% if @home_page %>
      <%=   render 'layouts/header-home' %>
    <% elsif @roomtype_page %>
      <%=  render 'layouts/header-roomtype' %>
    <% elsif @booking_page %>
      <%=  render 'layouts/header-booking' %>
    <% elsif @about_page %>
      <%=  render 'layouts/header-about' %>
    <% else %>
      <%=  render 'layouts/header' %>
    <% end %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/roomtype/index.html.erb
<div class="booking-body">
  <main class="site-main">
    <div class="rs" align="center">
      <br>
      <br>
      <table style=" width: 60%;border-radius: 15%">
        <tr>
          <th  width="250px" height="100">
            <h2>พักได้สูงสุด</h2>
          </th>
          <th height="100">
            <h2>ประเภทห้องพัก</h2>
          </th>
        </tr>
        <tr style="border: 0px solid black">
          <td style="border: 0px solid black">
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <a href="/roomtype/room1">Grand Garden Pavilion King Room</a>
            <br>
            1 คิงไซส์
          </td>
          <td align="right">
            <img src="/images/king.png" width="40" height="40">
          </td>
        </tr>

        <tr style="border: 0px solid black">
          <td style="border: 0px solid black">
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <a href="/roomtype/room2">Grand Garden Pavilion Twin Room</a>
            <br>
            2 เตียงเดี่ยว
          </td>
          <td align="right">
            <img src="/images/double.png" width="40" height="40">
          </td>
        </tr>

        <tr >
          <td >
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <a href="/roomtype/room3">Terrace Suite</a>
            <br>
            1 คิงไซส์
          </td>
          <td align="right">
            <img src="/images/king.png" width="40" height="40">
          </td>
        </tr>

        <tr >
          <td >
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <a href="/roomtype/room4">Ocean Delux Villa</a>
            <br>
            1 คิงไซส์
          </td>
          <td align="right">
            <img src="/images/king.png" width="40" height="40">
          </td>
        </tr>

        <tr >
          <td >
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <a href="/roomtype/room5">Beach Villa</a>
            <br>
            1 คิงไซส์
          </td>
          <td align="right">
            <img src="/images/king.png" width="40" height="40">
          </td>
        </tr>

        <tr >
          <td >
            <div align="center">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            <img src="/images/man.png" width="40" height="40">
            </div>
          </td>
          <td align="left">
            <table>
              <tr height="10">
                <a href="/roomtype/room6">La maison</a>
              </tr>
            </table>
            <table>
              <tr height="10">
                ห้องนอน 1: 1 คิงไซส์
              </tr>
            </table>
            <table>
              <tr height="10">
                หห้องนอน 2: 1 คิงไซส์
              </tr>
            </table>
            <table>
              <tr height="10">
                ห้องนั่งเล่น: 1 เตียงโซฟา
              </tr>
            </table>
          </td>
          <td align="right">
            <table>
              <tr height="20">
              </tr>
            </table>
            <table>
              <tr>
                <img src="/images/king.png" width="40" height="40">
              </tr>
            </table>
            <table>
              <tr>
                <img src="/images/king.png" width="40" height="40">
              </tr>
            </table>
            <table>
              <tr>
                <img src="/images/sofa.png" width="40" height="40">
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <br>
      <a style="
      display: block;
          text-decoration: none;
          color: white;
          padding: 10px 20px;
          border-radius: 8px;
          background-color: dimgray;
          width: 60px" href="/bookings/index">จองเลย</a></li><br>
    </div>

  </main>
</div>

app/views/roomtype/room1.erb
<div class="booking-body">
  <main class="site-main">
    <div align="center">
      <br>
      <h3>Grand Garden Pavilion King Room</h3>
      ขนาดห้อง 55 ม.²<br>
      ห้องเตียงใหญ่มีระเบียง โซฟา และมินิบาร์ พร้อมวิวสระว่ายน้ำ<br>
      ท่านที่จะเข้าพักต้องมีอายุตั้งแต่ 18 ปีขึ้นไป<br><br>
      <div class="room1">
        <div class="pic">
          <img src="/images/room/1/127533290.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533301.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533311.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533316.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533345.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533349.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533353.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533366.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="pic">
          <img src="/images/room/1/127533385.jpg" width="100%" style="border-radius: 20px">
        </div>
        <div class="head">
          <h4>สิ่งอำนวยความสะดวก</h4>
        </div>
        <div class="head">

        </div>
        <div class="head">

        </div>
        <div class="bod">
          <ul>
            <li>ระเบียง</li>
            <li>ทิวทัศน์</li>
            <li>วิวสวนหย่อม</li>
            <li>ลานระเบียง</li>
            <li>โทรทัศน์</li>
            <li>โทรศัพท์</li>
            <li>เครื่องเล่นดีวีดี</li>
            <li>ช่องรายการดาวเทียม</li>
            <li>โทรทัศน์จอแบน</li>
            <li>แท่นวาง iPod</li>
            <li>ตู้นิรภัย</li>
            <li>เครื่องปรับอากาศ</li>
            <li>เตารีด</li>
            <li>พื้นที่นั่งเล่น</li>
            <li>พัดลม</li>
          </ul>
        </div>
        <div class="bod">
          <ul>
            <li>โซฟา</li>
            <li>เครื่องอบผ้า</li>
            <li>ตู้หรือห้องเก็บเสื้อผ้า</li>
            <li>เตียงพับ</li>
            <li>เตียงโซฟา</li>
            <li>ห้องน้ำส่วนตัว</li>
            <li>เครื่องใช้ในห้องน้ำฟรี</li>
            <li>ฝักบัว</li>
            <li>อ่างอาบน้ำ</li>
            <li>โถสุขภัณฑ์พร้อมราวจับ</li>
            <li>พื้นที่อาบน้ำรองรับเก้าอี้รถเข็น</li>
            <li>พื้นที่อาบน้ำฝักบัวแบบวอล์กอิน</li>
            <li>ฝักบัวพร้อมเก้าอี้</li>
            <li>เครื่องเป่าผม</li>
            <li>เสื้อคลุมอาบน้ำ</li>
          </ul>
        </div>
        <div class="bod">
          <ul>
            <li>รองเท้าแตะ</li>
            <li>บิเดต์</li>
            <li>กระดาษชำระ</li>
            <li>มินิบาร์</li>
            <li>ตู้เย็น</li>
            <li>กาต้มน้ำไฟฟ้า</li>
            <li>เครื่องชงกาแฟ</li>
            <li>โต๊ะทานอาหาร</li>
            <li>เฟอร์นิเจอร์กลางแจ้ง</li>
            <li>พื้นที่รับประทานอาหารกลางแจ้ง</li>
            <li>บริการโทรปลุก</li>
            <li>ผ้าเช็ดตัว/ผ้าปูที่นอน (มีค่าธรรมเนียม)</li>
            <li>หนังสือ ดีวีดี หรือเพลงสำหรับเด็ก</li>

          </ul>
        </div>
      </div>
      <br>
      <a style="
      display: block;
          text-decoration: none;
          color: white;
          padding: 10px 20px;
          border-radius: 8px;
          background-color: dimgray;
          width: 60px" href="/bookings/index">จองเลย</a></li><br>
    </div>

  </main>
</div>

app/views/welcome/index.html.erb
<div class="topnav">
  <a href="#home">Home</a>
  <a class="active" href="#about">About</a>
</div>
<div class="content">
    <div class="container">
        <header>
        <h1><u>About</u></h1>
        </header>
        <s1>
        <h2> Team member </h2>
        <div class="groupname">
        กัญญาภรณ์ สร้อยคำพา 5910520054<br>
        วิศววิท ฤทธิศรธนู 5910613214<br>
        โฆษิต สุขบรรเทิง 5910613388<br>
        ธนพล บุญมาก 5910680379
        </div>
        <br>
        <br>
        <h2>Links</h2>
        <a href="https://drive.google.com/file/d/1u6TnvV_R2VMEPe9sHUn399EErXJepg51/view?usp=sharing"><button class="button button1">Proposal</button></a>
        <a href="https://gitlab.com/5910613388/layana"><button class="button button1">Git</button></a>
        <a href="https://www.pivotaltracker.com/n/projects/2406996"><button class="button button1">Pivotal tracker</button></a>
        </s1>
        <s2>
        <h2>User Story</h2>
        <div>
            <img src="1.jpg" width="35%">
            <img src="2.jpg" width="35%">
            <img src="6.jpg"width="35%">
            <img src="5.jpg"width="35%">
            <img src="4.jpg" width="35%">
            <img src="3.jpg" width="35%">
        </div>
        </s2>
    </div>
</div>